### ISSUE TITLE
The Core Infrastructure Initiative (CII) badge - Quality Section

### ISSUE THREAD

**Issue by robertwatkins** [javabeanz/owasp-security-logging#11]
This ticket is a child to #8 (see that issue for background information)

The two items marked as 'unknown' for this part of the certification are
- It is SUGGESTED that this policy on adding tests be documented in the instructions for change proposals. [tests_documented_added]  Hide details
  However, even an informal rule is acceptable as long as the tests are being added in practice.
  Tests documented added justification
- It is SUGGESTED that projects be maximally strict with warnings, but this is not always practical.

These two items should be reviewed and any project changes to address them should be implemented. When the team believes these are satisfied, the certification site can be updated and this ticket closed

**Comment by javabeanz** [comment]
quality part is covered
