### ISSUE TITLE
SecurityUtil.bindSystemStreamsToSLF4J()

### ISSUE THREAD

**Issue by JensPiegsa** [javabeanz/owasp-security-logging#16]
The [SecurityUtil](https://github.com/javabeanz/owasp-security-logging/blob/a8cd4f56489708b4ab85639cdff0f104a5f58195/owasp-security-logging-common/src/main/java/org/owasp/security/logging/util/SecurityUtil.java) class provides various useful features. However the benefit of `bindSystemStreamsToSLF4J` may be improved by adding a way to differentiate the noisy sysout/syserr from the other info logs produced by the same class. This could be achieved by introducing another Logger instance or at least allowing to adjust the log level.

Best regards,
Jens

**Comment by javabeanz** [comment]
thanks for your comment Jens ! do you have a pullrequest for the change you want ?
