### ISSUE TITLE
MaskingConverter does not work with MultiMarker

### ISSUE THREAD

**Issue by preichel-cg** [javabeanz/owasp-security-logging#19]
Dear all,
is it intended, that the ...mask.MaskingConverter only masks arguments of log events which **only** have the "Confidential" Marker? Since MultiMarkers are one of the main features of this package, I would expect them to be supported as well.
This would just require `eventMarker.contains(SecurityMarkers.CONFIDENTIAL)` instead of `eventMarker.equals(SecurityMarkers.CONFIDENTIAL)` in the `convert()` method.
Thank you for feedback.

**Comment by adetlefsen-rms** [comment]
@preichel-cg Thanks for bringing this to my attention! Do you want to send a PR and get contribution credit? If not, I will fix this ASAP.

**Comment by preichel-cg** [comment]
Ok great. Yes I will do that. Cheers.

**Comment by preichel-cg** [comment]
sorry, I thought the button would only close the comment window...

**Comment by preichel-cg** [comment]
@adetlefsen-rms Hi, here is the corresponding pull request: #20

**Comment by augustd** [comment]
@preichel-cg Thanks again for bringing this to our attention. I added a unit test for this condition in Logback and discovered that there were issues with the Log4J version as well. See #21 

Keep using the library and by all means keep contributing!

**Comment by preichel-cg** [comment]
@augustd looks good, this will certainly help me create my first unit test some time :-)
One question about using the library: when do you plan the next tag / release? I see on [github](https://github.com/javabeanz/owasp-security-logging/wiki/Usage-with-Logback) version 1.1.0 and on [maven](https://mvnrepository.com/artifact/org.owasp/security-logging) version 1.1.2, so maybe I am missing some info on how to use an even newer one as Maven dependency already?

Thanks!

**Comment by adetlefsen-rms** [comment]
We will get a new release out soon!

**Comment by augustd** [comment]
@preichel-cg, Version 1.1.3 has been released to Maven Central
