### ISSUE TITLE
library does not build with jdk 9

### ISSUE THREAD

**Issue by javabeanz** [javabeanz/owasp-security-logging#24]
...
[ERROR] Failed to execute goal com.buschmais.jqassistant.scm:jqassistant-maven-p
lugin:1.1.4:scan (default) on project security-logging: Execution default of goa
l com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.1.4:scan failed: Unab
le to load the mojo 'scan' in the plugin 'com.buschmais.jqassistant.scm:jqassist
ant-maven-plugin:1.1.4'. A required class is missing: javax/activation/DataSource

**Comment by augustd** [comment]
@spoofzu How does one get a Java9 JDK for testing?

**Comment by spoofzu** [comment]
Give this a try, https://jdk.java.net/ <https://jdk.java.net/>

Btw - I moved on from Oracle.  Working on my own now.

—Milton

**Comment by augustd** [comment]
Oddly enough, you can only get Mac versions of JDK 8 and 11. If JDK 9 is no longer supported, should this bug be updated for JDK 11?

**Comment by spoofzu** [comment]
Looks like public support for JDK 9 dropped March 2018.  Sustaining support (paid option) is available.  A non-Oracle JDK, OpenJDK 9.0.4, is free an available under GPL license if that’s helpful, https://jdk.java.net/archive/ <https://jdk.java.net/archive/>.
—Milton

**Comment by augustd** [comment]
Was able to use OpenJDK 9 to diagnose the issue. Looks like the package name for DataSource changed from `javax.activation` to `java.activation` and that caused a `ClassNotFoundException` on execution of the JQAssistant plugin. 

The newer version of JQAssistant plugin solves this problem and I've confirmed that it now builds under JDK 8 and 9.

**Comment by spoofzu** [comment]
Good detective work.  Sort of lucky too because OpenJDK and JDK are not necessarily the same code base.  Although I believe ORA said the code lines would converge in the future.  —Milton

Please excuse if terse.  Sent via mobile device.

**Comment by spoofzu** [comment]
Incidentally, and unrelated, I have considered an interesting future logging feature while reviewing OpenJDK code.  Here’s the idea, the design of the SecurityManager is such that it’s easy to design your own.  OpenJDK designers call the various methods of the active SecurityManager where an instance is available.  Calls are made within the Java platform to test opening files, opening sockets, process execution, virtually all risky calls.  I was thinking of designing a NullSecurityManager that wraps an existing SecurityManager, if one exists, and adds logging for permissions checks.  The way the SecurityManager works is that it’s possible to add support from command line parameters.  This means it’s possible to have AOP style injected security log messages in the Java platform without the normal risks and problems of AOP.  Adds security logging support to any existing code.  I still need to review platform code to see if any current logging is in place but I don’t remember seeing any.  Think this sounds interesting if include the feature?
—Milton

Please excuse if terse.  Sent via mobile device.

**Comment by javabeanz** [comment]
does this fit the enhancement https://github.com/javabeanz/owasp-security-logging/issues/5 ?

**Comment by spoofzu** [comment]
AOP is a broad and flexible approach to injecting code.  The SecurityManager is an extensible access control feature.  It’s not designed with logging in mind but it provides some advantages to facilitate logging within the platform.  Most noteworthy is that the methods of SecurityManager are called throughout the platform when creating files, opening sockets, etc.  It’s an easy place for us to include some logging.  It’s not exactly AOP but like AOP it’s called in many places we desire logging like testing access control privileges.  Because the SecurityManager framework is built into the platform already we only need to tell it to log.  Since the SecurityManager can be specified on the command line, no code changes are required in legacy code for basic privilege logging.
  —Milton

Please excuse if terse.  Sent via mobile device.

**Comment by augustd** [comment]
@spoofzu please add a new issue for the idea of overriding the SecurityManager to add logging so we don't lose track of it now that this one is closed.

**Comment by spoofzu** [comment]
Yes, I will follow-up.  Thanks.  —Milton

Please excuse if terse.  Sent via mobile device.
