### ISSUE TITLE
automated release to Maven official repository

### ISSUE THREAD

**Issue by javabeanz** [javabeanz/owasp-security-logging#32]

**Comment by augustd** [comment]
Is this as simple as setting `<autoReleaseAfterClose>true</autoReleaseAfterClose>` in pom.xml? 

@javabeanz @spoofzu If you want the ability to deploy you will need to register keys and get added to the project at https://oss.sonatype.org

**Comment by javabeanz** [comment]
here is a recipe : https://synyx.de/blog/2018-01-24-travisci-github-releases/
autoReleaseAfterClose does indeed suggest this should to the trick too. I do have a sonatype account.

**Comment by javabeanz** [comment]
Well done August !
