### ISSUE TITLE
Replacement for VersionEye

### ISSUE THREAD

**Issue by augustd** [javabeanz/owasp-security-logging#38]
VersionEye is no more. See: https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/

Snyk.io may be a good replacement: https://snyk.io

**Comment by javabeanz** [comment]
Snyk is now monitoring this project. Its dashboard only shows vulns per pom, giving 4 badges. This is for the top pom :                 
[![Known Vulnerabilities](https://snyk.io/test/github/javabeanz/owasp-security-logging/badge.svg?targetFile=pom.xml)](https://snyk.io/test/github/javabeanz/owasp-security-logging?targetFile=pom.xml)
