### ISSUE TITLE
Exclude tests from code quality report 

### ISSUE THREAD

**Issue by augustd** [javabeanz/owasp-security-logging#46]
Many of the issues in the Codacy code quality report are reported on test code. Test code should be excluded to produce an accurate report on the final code library.

**Comment by javabeanz** [comment]
good point ! how can this be done ? is it some <exclude>  rule in the pom ?

**Comment by javabeanz** [comment]
https://support.codacy.com/hc/en-us/articles/360005097654-Ignore-files-from-Codacy-analysis
this could help; looking into this later

**Comment by javabeanz** [comment]
fixing Travis build is giving me a headache.

**Comment by javabeanz** [comment]
i  have fixed the build, and added codacy ignore rule, but no improveent on quality,,,,

**Comment by javabeanz** [comment]
i checked the codacy report (https://codecov.io/gh/javabeanz/owasp-security-logging) but the poor rating comes from solely production code. closing this isseu and creating a new one to boost codacy score
