### ISSUE TITLE
Masking not working with logback in spring boot

### ISSUE THREAD

**Issue by stackoverflow2** [javabeanz/owasp-security-logging#51]
i am trying this
    log.info(SecurityMarkers.CONFIDENTIAL, "password={}","asd");
output is:
2020-05-21 13:37:55.472  INFO INFOid --- [nio-8080-exec-1] c.m.b.e.r.ConsumerApi                    : password=asd

**Comment by augustd** [comment]
It could be a configuration issue. Can you please post your logback.xml?

**Comment by stackoverflow2** [comment]
Hi @augustd thanks for replying.I'm not using any logback.xml file default configuration i am using.
is there any configuration needed in logback.xml ? If yes, please post here. I didn't  find any documentation regarding this.

**Comment by augustd** [comment]
Config information is in the wiki: https://github.com/javabeanz/owasp-security-logging/wiki/Masking

You need to create a logback.xml and setup masking.

**Comment by javabeanz** [comment]
@stackoverflow2 if the documentation did not solve your problem, please reopen this one
