### ISSUE TITLE
Logback log injection

### ISSUE THREAD

**Issue by iluwatar** [javabeanz/owasp-security-logging#59]
https://github.com/javabeanz/owasp-security-logging/wiki/Log-Forging describes the provided `CRLFConverter` class to prevent log forging. However this converter is not sufficient since there are other characters beside `\n` and `\r` that should be filtered out, for example the unicode character U+0085 (next line) is one of these.

**Comment by javabeanz** [comment]
good point, the converter should filter more characters. do you have an idea how to implement a fix ?

**Comment by bitsal** [comment]
With current implementation log statement with exception trace becomes not readable

**Comment by javabeanz** [comment]
for strack traces there is a renderer : https://github.com/nlog/NLog/wiki/Stack-Trace-Layout-Renderer. does this solve your problem ?

**Comment by bitsal** [comment]
how to use it in conjunction with CRLFConverter?

**Comment by spoofzu** [comment]
We include [CRLRConverters](https://github.com/javabeanz/owasp-security-logging/blob/master/owasp-security-logging-logback/src/main/java/org/owasp/security/logging/mask/CRLFConverter.java).

**Comment by augustd** [comment]
@iluwatar Do you have a list of other newline characters that should be filtered out? Feel free to send a pull request of you are so inclined.
