### ISSUE TITLE
The Core Infrastructure Initiative (CII) badge - Reporting Section

### ISSUE THREAD

**Issue by robertwatkins** [javabeanz/owasp-security-logging#9]
This ticket is a child to #8 (see that issue for background information)

The two items marked as 'unknown' for this part of the certification are
- The project MUST acknowledge a majority of bug reports submitted in the last 2-12 months (inclusive); the response need not include a fix.
  - The project SHOULD respond to most enhancement requests in the last 2-12 months (inclusive). The project MAY choose not to respond.

These two items should be reviewed and any project changes to address them should be implemented. When the team believes these are satisfied, the certification site can be updated and this ticket closed

**Comment by robertwatkins** [comment]
Here is the text that I'd like to put on the wiki Contribution page ( https://github.com/javabeanz/owasp-security-logging/wiki/Contribution-guidelines ) to resolve this ticket.

I'd also like to change the name to 'Contributions/Requests/Bugs'

@augustd  @javabeanz  @spoofzu @adetlefsen-rms  Do you have any objections or feedback to this recommendation?

-----------------------
**Bug Reports**
Thanks for letting us know about issues with the code. Please include the following information when submitting a bug report:
 - Detailed steps to recreate
 - Expected Results
 - Actual Results
 - jdk/jre details
 - OS
 - name or type (web app, web service, standalone app, etc.)  of application
 - logging toolset (log4j, logback)

The project team will be notified of new bug reports and will respond within 1 week (Ideally, within a couple days though). The response will generally result in an acknowledgement that we received the the report and that it will be assigned to someone to review to determine the next steps.

**Enhancement Requests**
Community participation is the key to our success. If you have an enhancement to this project, please provide the following information:
 - What is the use case?
 - Any information on specific changes to the API
 - Success Criteria

The project team will be notified of enhancement requests and will respond within 2 weeks. The response will generally be one of the following 1)yes, and we need more information to continue 2)yes, we have enough information and will prioritize this 3)unsure and we need more information to be able to decide or 4)no, with some description as to why.

**Comment by javabeanz** [comment]
Sounds like a good proposal; its also good to know the version the security logging library. 
I would make the threshold for participation as low as possible, but not lower. Maybe drop the success criteria ?

**Comment by augustd** [comment]
This looks good to me. We can always amend it later -This is an open source project, not corporate governance.

**Comment by spoofzu** [comment]
Looks good to me also.

**Comment by robertwatkins** [comment]
Thanks for the feedback. I've made the changes

@javabeanz do you have the ability to modify the coreinfrastructure.org site settings? Once that is done, this ticket is completed.

**Comment by javabeanz** [comment]
reporting section is covered
